apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-sf7d
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-xdhe-tenant/rhtap-demo-app/hacbs-test-project-sf7d@sha256:6a5455ee810231933a02f3940f79b2db637dc1db0210ec62630dba1f452760fa
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
