apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-sf7d
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-xdhe-tenant/rhtap-demo-app/hacbs-test-project-sf7d@sha256:6f11b21c4a3007f3e81dc258d7ed2b0a12def3c95607b232881a434dbcf793d4
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
